# Generated by Django 3.2 on 2023-05-14 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_pictures', to='testimonials.service')),
            ],
        ),
    ]
